import test from 'node:test';import assert from 'node:assert/strict';
import {arithmeticTask,duelTask,awardDuel,calculate,mathChoices,type MathOperation,type MathLevel} from './mathPracticeModel';
const rngs=[()=>0,()=>.999999,()=>.5,Math.random];
test('Arithmetic choices always terminate, are distinct and contain the true answer including zero',()=>{for(const rng of rngs)for(let answer=0;answer<500;answer++){const choices=mathChoices(answer,rng);assert.equal(choices.length,3);assert.equal(new Set(choices).size,3);assert(choices.includes(answer));assert(choices.every(x=>Number.isInteger(x)&&x>=0));}});
test('Arithmetic respects the selected range and whole-number division',()=>{for(const rng of rngs)for(const op of ['+','−','×','÷'] as MathOperation[])for(const range of [10,100])for(let i=0;i<50;i++){const t=arithmeticTask(op,range,rng);assert.equal(t.answer,calculate(t.left,t.op,t.right));assert(Number.isInteger(t.answer));assert(t.answer>=0);if(op==='+'||op==='−'){assert(t.left<=range&&t.right<=range&&t.answer<=range);}else assert(t.right>0);assert(t.choices.includes(t.answer));}});
test('Duel always has valid solutions and awards the actual winning team',()=>{for(const rng of rngs)for(const level of ['easy','medium','hard'] as MathLevel[])for(const op of ['mixed','+','−','×','÷'] as const){const t=duelTask(level,op,rng);assert.equal(t.answer,calculate(t.left,t.op,t.right));assert(Number.isInteger(t.answer)&&t.answer>=0);assert(t.choices.includes(t.answer));}assert.deepEqual(awardDuel([4,3],1),{scores:[4,4],winner:null});assert.deepEqual(awardDuel([4,4],1),{scores:[4,5],winner:1});assert.deepEqual(awardDuel([4,4],0),{scores:[5,4],winner:0});});

import {generateChainTask,DEFAULT_KOPFRECHEN_SETTINGS} from './mentalMathAlgorithm';
test('The active chain fallback preserves every selected operation and length',()=>{for(const op of ['+','-','×','÷'] as const)for(const chainLength of [2,3,4,5] as const)for(const rng of [()=>0,()=>.999999]){const t=generateChainTask({...DEFAULT_KOPFRECHEN_SETTINGS,mode:'chain',chainLength,chainDifficulty:'hard',chainOperators:[op]},rng);assert.equal(t.steps!.length,chainLength);let value=t.startValue!;for(const step of t.steps!){assert.equal(step.op,op);assert(step.operand>0);value=step.op==='+'?value+step.operand:step.op==='-'?value-step.operand:step.op==='×'?value*step.operand:value/step.operand;assert(Number.isInteger(value)&&value>=0);assert.equal(step.subtotal,value);}assert.equal(t.correctAnswer,value);}});
