import React from 'react';
import { 
  Zap, 
  ListOrdered, 
  HelpCircle, 
  Lightbulb, 
  AlertCircle,
  Check,
  BookOpen,
  Volume2,
  RefreshCw,
  Eye,
  SkipForward,
  CornerDownRight,
  Calculator,
  Layers,
  ArrowRight,
  Hand,
  TrendingDown,
  Hash,
  Grid,
  RotateCw,
  ArrowLeftRight,
  MoveHorizontal,
  Star,
  Repeat,
  PlusCircle,
  Copy,
  PlusSquare,
  Search,
  Link2,
  Sparkles,
  EyeOff,
  Music,
  Scissors,
  Wand2,
  Type,
  Split,
  MessageSquare,
  Target,
  ShieldCheck,
  CheckSquare,
  Compass,
  PenTool,
  Move,
  CheckCircle2,
  Crosshair,
  Activity,
  Maximize2,
  Sliders,
  Feather,
  Users,
  UserCheck,
  Heart,
  Smile,
  MessageCircle,
  Brain,
  Clock,
  Briefcase,
  ThumbsUp,
  Scale
} from 'lucide-react';
import { DiagnosticObservationTag } from '../../../types/diagnosticCore';

interface DiagnosticObservationPanelProps {
  selectedTags: DiagnosticObservationTag[];
  onToggleTag: (tag: DiagnosticObservationTag) => void;
  availableTags?: DiagnosticObservationTag[];
  teacherNote?: string;
  onChangeTeacherNote?: (note: string) => void;
}

export const TAG_CONFIG: Record<string, {
  label: string;
  icon: React.FC<{ className?: string }>;
  activeBg: string;
  activeBorder: string;
  activeText: string;
  description: string;
}> = {
  // General & Mengen
  instant: {
    label: 'Sofort / Automatisiert',
    icon: Zap,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Blitzartiger Abruf ohne Zögern (< 2-3 Sek.)',
  },
  strategy_used: {
    label: 'Strategie genutzt',
    icon: Lightbulb,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Nutzt Rechenvorteil, Hilfsaufgabe oder Struktur',
  },
  calculated: {
    label: 'Gerechnet (Schrittweise)',
    icon: Calculator,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Schrittweise im Kopf hergeleitet',
  },
  counted: {
    label: 'Gezählt',
    icon: ListOrdered,
    activeBg: 'bg-amber-500',
    activeBorder: 'border-amber-600',
    activeText: 'text-white',
    description: 'Zählt die Elemente einzeln mit Blick oder Sprache ab',
  },
  hesitant: {
    label: 'Unsicher / Zögernd',
    icon: HelpCircle,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Zögert spürbar oder korrigiert sich mehrfach',
  },
  needs_hint: {
    label: 'Braucht Hinweis',
    icon: AlertCircle,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Benötigte gezielten Impuls oder Unterstützung',
  },

  // Zehnerübergang
  decomposes_meaningful: {
    label: 'Zerlegt zur 10 (Stopp bei 10)',
    icon: Layers,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Zerlegt zweiten Summanden zum Zehner (z. B. 8+2+3)',
  },
  bridges_to_ten: {
    label: 'Ergänzt zum Zehner',
    icon: ArrowRight,
    activeBg: 'bg-cyan-600',
    activeBorder: 'border-cyan-700',
    activeText: 'text-white',
    description: 'Erkennt und nutzt gezielt die Ergänzung zum Zehner',
  },
  uses_near_double: {
    label: 'Nachbaraufgabe / Verdopplung',
    icon: RefreshCw,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Nutzt Verdopplungsnähe (z. B. 7+6 über 6+6+1)',
  },
  counts_on: {
    label: 'Zählt weiter (ab 1. Zahl)',
    icon: ListOrdered,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Startet bei erster Zahl und zählt in Einzelschritten weiter',
  },
  counts_on_fingers: {
    label: 'Zählt an Fingern',
    icon: Hand,
    activeBg: 'bg-amber-700',
    activeBorder: 'border-amber-800',
    activeText: 'text-white',
    description: 'Nutzt Finger als Zählhilfe',
  },
  counts_back: {
    label: 'Rechnet / Zählt rückwärts',
    icon: TrendingDown,
    activeBg: 'bg-orange-600',
    activeBorder: 'border-orange-700',
    activeText: 'text-white',
    description: 'Zählt bei Subtraktion einzeln rückwärts',
  },
  strategy_switched: {
    label: 'Strategie gewechselt',
    icon: RefreshCw,
    activeBg: 'bg-purple-600',
    activeBorder: 'border-purple-700',
    activeText: 'text-white',
    description: 'Hat während des Rechnens den Rechenweg angepasst',
  },

  // Leseflüssigkeit
  fluent: {
    label: 'Flüssig gelesen',
    icon: BookOpen,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Müheloser, gleichmäßiger und stockungsarmer Lesefluss',
  },
  meaningful_phrasing: {
    label: 'Sinnvolle Phrasierung',
    icon: Volume2,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Gliedert in Sinneinheiten, beachtet Satzzeichen',
  },
  halting: {
    label: 'Stockend / Verlangsamt',
    icon: HelpCircle,
    activeBg: 'bg-amber-500',
    activeBorder: 'border-amber-600',
    activeText: 'text-white',
    description: 'Wort-für-Wort-Lesen mit häufigen Pausen',
  },
  spelling_out: {
    label: 'Buchstabierend / Lautierend',
    icon: AlertCircle,
    activeBg: 'bg-rose-600',
    activeBorder: 'border-rose-700',
    activeText: 'text-white',
    description: 'Setzt Wörter mühsam Einzellaut für Einzellaut zusammen',
  },
  frequent_self_correction: {
    label: 'Häufige Selbstkorrektur',
    icon: RefreshCw,
    activeBg: 'bg-indigo-500',
    activeBorder: 'border-indigo-600',
    activeText: 'text-white',
    description: 'Bemerkt und korrigiert Lesefehler eigenständig',
  },
  skips_words: {
    label: 'Überspringt Wörter / Endungen',
    icon: SkipForward,
    activeBg: 'bg-orange-600',
    activeBorder: 'border-orange-700',
    activeText: 'text-white',
    description: 'Lässt Wörter, Wortteile oder Endungen aus',
  },
  loses_line: {
    label: 'Verliert die Zeile',
    icon: CornerDownRight,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Verrutscht beim Zeilenwechsel',
  },

  // Zahlenraum & Stellenwert (Schritt 6)
  number_concept_secure: {
    label: 'Zahlvorstellung sicher',
    icon: Hash,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Hat sichere Mengenvorstellung und Zahlordnung',
  },
  place_value_secure: {
    label: 'Stellenwert sicher',
    icon: Layers,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Versteht Stellenwertlogik (E/Z/H/T) und Nullen sicher',
  },
  uses_grouping: {
    label: 'Nutzt Bündelung',
    icon: Grid,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Fasst 10er-/100er-Bündel gezielt zusammen',
  },
  needs_material: {
    label: 'Braucht Anschauung/Material',
    icon: HelpCircle,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Benötigt konkretes Dienes-Material oder Zehnerfeld',
  },
  counts_stepwise: {
    label: 'Zählt in Einzelschritten',
    icon: ListOrdered,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Zählt noch einzeln statt in Bündeln zu denken',
  },
  confuses_places: {
    label: 'Verwechselt Stellenwerte',
    icon: Split,
    activeBg: 'bg-rose-600',
    activeBorder: 'border-rose-700',
    activeText: 'text-white',
    description: 'Verwechselt z. B. Zehner und Einer (34 als 43)',
  },
  digit_reversal: {
    label: 'Zahlendreher',
    icon: ArrowLeftRight,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Verdreht die Ziffernreihenfolge beim Sprechen/Schreiben',
  },
  number_line_secure: {
    label: 'Zahlenstrahl sicher',
    icon: MoveHorizontal,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Orientiert sich fehlerfrei auf dem Zahlenstrahl',
  },

  // Multiplikation / Einmaleins (Schritt 6)
  core_fact_used: {
    label: 'Kernaufgabe genutzt',
    icon: Star,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Nutzt Stützpunktaufgaben (1x, 2x, 5x, 10x)',
  },
  commutative_used: {
    label: 'Tauschaufgabe genutzt',
    icon: Repeat,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Nutzt Kommutativgesetz (z. B. 3x8 = 8x3)',
  },
  near_fact_used: {
    label: 'Nachbaraufgabe (+1x/-1x)',
    icon: PlusCircle,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Leitet von Nachbaraufgabe ab (z. B. 6x7 = 5x7 + 7)',
  },
  double_half_used: {
    label: 'Verdoppeln / Halbieren',
    icon: Copy,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Verdoppelt Kernaufgabe (z. B. 4x6 = 2x(2x6))',
  },
  repeated_addition: {
    label: 'Wiederholte Addition',
    icon: PlusSquare,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Rechnet als Plus-Kette (z. B. 4+4+4+4)',
  },

  // Leseverständnis (Schritt 6)
  finds_information: {
    label: 'Findet Information gezielt',
    icon: Search,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Lokalisiert gesuchte Textstelle zielsicher',
  },
  rereads_text: {
    label: 'Liest zielgerichtet nach',
    icon: Eye,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Überprüft Antwort durch gezieltes Nachlesen',
  },
  connects_information: {
    label: 'Verknüpft Textdetails',
    icon: Link2,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Kombiniert Informationen aus mehreren Sätzen',
  },
  draws_inference: {
    label: 'Zieht Schlussfolgerung',
    icon: Sparkles,
    activeBg: 'bg-purple-600',
    activeBorder: 'border-purple-700',
    activeText: 'text-white',
    description: 'Erfasst implizite Zusammenhänge & Kausalität',
  },
  answers_from_memory: {
    label: 'Antwortet aus Gedächtnis',
    icon: BookOpen,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Gibt Gelesenes korrekt ohne Nachschlagen wieder',
  },
  overlooks_information: {
    label: 'Übersieht Textdetails',
    icon: EyeOff,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Überliest wichtige Schlüsselwörter oder Fakten',
  },
  guesses: {
    label: 'Rät ohne Textbezug',
    icon: HelpCircle,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Antwortet spekulativ ohne Bezug zum Text',
  },
  does_not_understand_question: {
    label: 'Versteht Frage nicht',
    icon: AlertCircle,
    activeBg: 'bg-rose-600',
    activeBorder: 'border-rose-700',
    activeText: 'text-white',
    description: 'Benötigt Umformulierung der Fragestellung',
  },

  // Phonologische Bewusstheit (Schritt 6)
  rhyme_secure: {
    label: 'Reime sicher',
    icon: Music,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Erkennt und bildet Reimwörter sicher',
  },
  syllable_secure: {
    label: 'Silben sicher',
    icon: ListOrdered,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Klatscht und segmentiert Silben fehlerfrei',
  },
  initial_sound_secure: {
    label: 'Anlaut sicher',
    icon: ArrowRight,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Isoliert den ersten Laut eines Wortes korrekt',
  },
  final_sound_secure: {
    label: 'Endlaut sicher',
    icon: CornerDownRight,
    activeBg: 'bg-cyan-600',
    activeBorder: 'border-cyan-700',
    activeText: 'text-white',
    description: 'Bestimmt den Auslaut präzise',
  },
  phoneme_blending_secure: {
    label: 'Lautsynthese sicher',
    icon: Wand2,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Zieht Einzellaute flüssig zu einem Wort zusammen',
  },
  phoneme_segmentation_secure: {
    label: 'Lautanalyse sicher',
    icon: Scissors,
    activeBg: 'bg-purple-600',
    activeBorder: 'border-purple-700',
    activeText: 'text-white',
    description: 'Zerlegt Wörter vollständig in Einzellaute',
  },
  confuses_sound_and_letter_name: {
    label: 'Laut/Buchstabe verwechselt',
    icon: Type,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Spricht Buchstabennamen (z.B. "em") statt Laut (/m/)',
  },

  // --------------------------------------------------------------------------
  // LERNVORAUSSETZUNGEN (Schritt 11)
  // --------------------------------------------------------------------------
  // 1. Aufmerksamkeit
  stays_focused: {
    label: 'Bleibt fokussiert',
    icon: Target,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Hält Aufmerksamkeit über den Aufgabenzeitraum stabil aufrecht',
  },
  works_systematically: {
    label: 'Systematisches Vorgehen',
    icon: Grid,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Arbeitet strukturiert von links nach rechts / oben nach unten',
  },
  distractible: {
    label: 'Leicht ablenkbar',
    icon: EyeOff,
    activeBg: 'bg-amber-500',
    activeBorder: 'border-amber-600',
    activeText: 'text-white',
    description: 'Lässt sich durch Umgebungsreize oder Nebensächlichkeiten ablenken',
  },
  impulsive_response: {
    label: 'Reagiert vorschnell',
    icon: Zap,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Antwortet impulsiv ohne vollständiges Prüfen der Aufgabe',
  },
  misses_targets: {
    label: 'Übersieht Zielreize',
    icon: Crosshair,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Lässt relevante Zielobjekte oder Details aus',
  },
  rule_kept: {
    label: 'Regel sicher beibehalten',
    icon: ShieldCheck,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Hält Arbeitsregel auch bei Störreizen zuverlässig ein',
  },
  rule_lost: {
    label: 'Verliert Regel',
    icon: AlertCircle,
    activeBg: 'bg-rose-600',
    activeBorder: 'border-rose-700',
    activeText: 'text-white',
    description: 'Vergisst oder verwechselt die vorgegebene Handlungsregel',
  },
  fatigue_observed: {
    label: 'Ermüdung im Verlauf',
    icon: TrendingDown,
    activeBg: 'bg-slate-600',
    activeBorder: 'border-slate-700',
    activeText: 'text-white',
    description: 'Aufmerksamkeit / Genauigkeit sinkt gegen Ende der Serie',
  },

  // 2. Arbeitsgedächtnis
  recalls_sequence: {
    label: 'Erinnert Sequenz',
    icon: ListOrdered,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Gibt Reihenfolge der Elemente vollständig und richtig wieder',
  },
  keeps_order: {
    label: 'Reihenfolge exakt',
    icon: CheckCircle2,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Behält genaue Position und Abfolge im Gedächtnis',
  },
  rehearses: {
    label: 'Spricht innerlich mit',
    icon: Volume2,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Nutzt subvokales Wiederholen als aktive Merkstrategie',
  },
  groups_information: {
    label: 'Nutzt Bündelung/Chunking',
    icon: Layers,
    activeBg: 'bg-purple-600',
    activeBorder: 'border-purple-700',
    activeText: 'text-white',
    description: 'Fasst Informationseinheiten strukturiert zusammen (z.B. 2er-Gruppen)',
  },
  loses_order: {
    label: 'Verliert Reihenfolge',
    icon: HelpCircle,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Elemente werden genannt, aber in vertauschter Reihenfolge',
  },
  forgets_steps: {
    label: 'Vergisst Teilschritte',
    icon: SkipForward,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Führt nur Teil der mehrschrittigen Anweisung aus',
  },
  uses_strategy: {
    label: 'Nutzt Merkstrategie',
    icon: Lightbulb,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Wendet eigenständig visuelle oder sprachliche Merkhilfen an',
  },

  // 3. Visuelle Wahrnehmung
  visual_discrimination_secure: {
    label: 'Visuell sicher differenziert',
    icon: Eye,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Unterscheidet feine optische Details und Zeichen mühelos',
  },
  systematic_scan: {
    label: 'Systematischer Blickverlauf',
    icon: Search,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Durchsucht das Feld zeilen- oder spaltenweise strukturiert',
  },
  finds_difference: {
    label: 'Findet Unterschiede rasch',
    icon: CheckSquare,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Erkennt Abweichungen zielsicher ohne langes Suchen',
  },
  overlooks_details: {
    label: 'Übersieht Details',
    icon: EyeOff,
    activeBg: 'bg-amber-500',
    activeBorder: 'border-amber-600',
    activeText: 'text-white',
    description: 'Übergeht feine Konturen oder Ausrichtungen (z.B. Strich oben vs. unten)',
  },
  confuses_similar_symbols: {
    label: 'Verwechselt optisch ähnliche Zeichen',
    icon: AlertCircle,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Verwechselt b/d, p/q oder ähnliche geometrische Symbole',
  },
  loses_place: {
    label: 'Verliert Zeile / Suchort',
    icon: CornerDownRight,
    activeBg: 'bg-rose-600',
    activeBorder: 'border-rose-700',
    activeText: 'text-white',
    description: 'Verrutscht im Suchfeld oder verliert den Überblick',
  },
  needs_more_time: {
    label: 'Braucht mehr Betrachtungszeit',
    icon: HelpCircle,
    activeBg: 'bg-slate-500',
    activeBorder: 'border-slate-600',
    activeText: 'text-white',
    description: 'Benötigt spürbar längere Zeit zur optischen Analyse',
  },

  // 4. Raum-Lage
  left_right_secure: {
    label: 'Links / Rechts sicher',
    icon: ArrowLeftRight,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Unterscheidet rechts und links am Bild oder Raster sicher',
  },
  spatial_relation_secure: {
    label: 'Lagebeziehungen sicher',
    icon: Compass,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Beherrscht oben/unten, vor/hinter, zwischen, neben präzise',
  },
  rotation_secure: {
    label: 'Drehung sicher erfasst',
    icon: RotateCw,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Erkennt gedrehte und gespiegelte Figuren im Kopf',
  },
  uses_reference_point: {
    label: 'Nutzt Orientierungsmarke',
    icon: Target,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Orientiert sich an Fixpunkten (z.B. Rand, Mitte, Zeigefinger)',
  },
  confuses_left_right: {
    label: 'Verwechselt links / rechts',
    icon: ArrowLeftRight,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Spiegelt Richtungsangaben oder vertauscht rechts/links',
  },
  confuses_rotation: {
    label: 'Schwierigkeit bei Drehung/Spiegelung',
    icon: RotateCw,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Unsicherheit bei 90°/180°-Drehungen oder Spiegelachsen',
  },
  needs_physical_orientation: {
    label: 'Dreht Kopf / Körper mit',
    icon: Move,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Nutzt körperliche Mitbewegung zur Orientierung',
  },

  // 5. Feinmotorik
  precise_grip: {
    label: 'Präziser Pinzettengriff',
    icon: Hand,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Greift Kleinteile isoliert mit Daumen- und Zeigefingerkuppe',
  },
  hand_eye_coordination: {
    label: 'Hand-Auge-Koordination sicher',
    icon: CheckCircle2,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Steuert Werkzeuge (Schere, Faden, Stift) zielsicher',
  },
  bilateral_coordination: {
    label: 'Beidhändige Abstimmung gut',
    icon: Activity,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Haltehand und Arbeitshand arbeiten harmonisch zusammen',
  },
  controlled_movement: {
    label: 'Kontrollierte Kraftdosierung',
    icon: Sliders,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Dosiert Krafteinsatz beim Falten, Kneten und Schneiden angemessen',
  },
  awkward_grip: {
    label: 'Ungünstiger Griff / Faustgriff',
    icon: Hand,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Greift mit ganzer Hand oder unökonomischer Fingerhaltung',
  },
  drops_objects: {
    label: 'Gegenstände entgleiten',
    icon: TrendingDown,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Schwierigkeiten beim Halten oder Loslassen von Kleinteilen',
  },
  slow_execution: {
    label: 'Stark verlangsamte Ausführung',
    icon: HelpCircle,
    activeBg: 'bg-slate-500',
    activeBorder: 'border-slate-600',
    activeText: 'text-white',
    description: 'Ausführung benötigt überdurchschnittlich viel Zeit',
  },
  needs_assistance: {
    label: 'Braucht manuelle Hilfe',
    icon: AlertCircle,
    activeBg: 'bg-rose-600',
    activeBorder: 'border-rose-700',
    activeText: 'text-white',
    description: 'Benötigt Unterstützung beim Führen oder Halten des Materials',
  },

  // 6. Graphomotorik
  grip_functional: {
    label: 'Funktionale Stifthaltung',
    icon: PenTool,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Lockerer Dreipunktgriff mit freier Fingerbeweglichkeit',
  },
  line_control_secure: {
    label: 'Linienführung sicher',
    icon: Feather,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Spurgetreue Linien, saubere Bögen und Ecken',
  },
  movement_fluid: {
    label: 'Flüssiger Schreibfluss',
    icon: Zap,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Gleichmäßiger Bewegungsrhythmus ohne ständiges Absetzen',
  },
  size_consistent: {
    label: 'Größenkonstanz stabil',
    icon: Maximize2,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Hält Buchstabengröße und Lineaturhöhe gleichmäßig ein',
  },
  pressure_appropriate: {
    label: 'Schreibdruck angemessen',
    icon: Sliders,
    activeBg: 'bg-purple-600',
    activeBorder: 'border-purple-700',
    activeText: 'text-white',
    description: 'Gut sichtbare Linien ohne Durchdrücken des Papiers',
  },
  grip_tense: {
    label: 'Verkrampfte Stifthaltung',
    icon: AlertCircle,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Fingerknöchel weiß / überstreckt, starre Finger',
  },
  excessive_pressure: {
    label: 'Zu starker Schreibdruck',
    icon: TrendingDown,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Drückt Papier durch oder bricht Stiftminen ab',
  },
  weak_pressure: {
    label: 'Zu schwacher Schreibdruck',
    icon: Feather,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Sehr blasse, kaum lesbare Linienführung',
  },
  movement_stiff: {
    label: 'Starre Bewegung aus dem Arm',
    icon: Move,
    activeBg: 'bg-rose-600',
    activeBorder: 'border-rose-700',
    activeText: 'text-white',
    description: 'Schreibt mit starrem Handgelenk aus Schulter/Ellenbogen',
  },
  needs_repositioning: {
    label: 'Haltungskorrektur nötig',
    icon: Sliders,
    activeBg: 'bg-slate-600',
    activeBorder: 'border-slate-700',
    activeText: 'text-white',
    description: 'Sitzhaltung oder Blattneigung muss angepasst werden',
  },

  needs_repetition: {
    label: 'Braucht Wiederholung',
    icon: RefreshCw,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Aufgabenstellung / Wort musste wiederholt werden',
  },

  // =========================================================================
  // 7. ARBEITSVERHALTEN (sl-arbeitsverhalten)
  // =========================================================================
  starts_independently: {
    label: 'Startet selbstständig',
    icon: Zap,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Beginnt nach Erklärung sofort ohne Zögern mit der Arbeit',
  },
  starts_after_orientation: {
    label: 'Beginnt nach Orientierung',
    icon: Compass,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Benötigt kurze Einlese- oder Sortierphase und fängt dann an',
  },
  works_independently: {
    label: 'Arbeitet selbstständig',
    icon: CheckCircle2,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Führt die Schritte ohne kontinuierliche Begleitung aus',
  },
  asks_targeted_help: {
    label: 'Fragt gezielt nach',
    icon: HelpCircle,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Holt sich bei konkreten Unklarheiten zielgerichtet Hilfe',
  },
  stays_with_task: {
    label: 'Bleibt ausdauernd dran',
    icon: Clock,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Hält die Konzentration über die gesamte Arbeitszeit aufrecht',
  },
  works_with_breaks: {
    label: 'Arbeitet mit kurzen Pausen',
    icon: RefreshCw,
    activeBg: 'bg-slate-600',
    activeBorder: 'border-slate-700',
    activeText: 'text-white',
    description: 'Setzt kurz ab, findet aber selbstständig zurück in die Arbeit',
  },
  organizes_material: {
    label: 'Organisiert Material gut',
    icon: Briefcase,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Hält benötigte Arbeitsmittel griffbereit und einsatzbereit',
  },
  material_ready: {
    label: 'Material vorbereitet',
    icon: CheckSquare,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Arbeitsmittel liegen ordentlich und passend bereit',
  },
  tidy_workplace: {
    label: 'Übersichtlicher Arbeitsplatz',
    icon: Grid,
    activeBg: 'bg-cyan-600',
    activeBorder: 'border-cyan-700',
    activeText: 'text-white',
    description: 'Hält den Tisch strukturiert frei von störenden Dingen',
  },
  checks_work: {
    label: 'Prüft eigene Ergebnisse',
    icon: Search,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Kontrolliert Arbeitsergebnisse selbstständig auf Richtigkeit',
  },
  corrects_errors: {
    label: 'Korrigiert Fehler eigenständig',
    icon: Lightbulb,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Bessert gefundene Fehler ohne Frust oder Zögern aus',
  },
  tries_again: {
    label: 'Probiert erneut bei Fehlern',
    icon: RotateCw,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Zeigt Ausdauer und startet einen zweiten Lösungsversuch',
  },
  appropriate_work_pace: {
    label: 'Angemessenes Arbeitstempo',
    icon: Activity,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Arbeitet weder überhastet noch trödelnd im passenden Tempo',
  },
  handles_distractions_well: {
    label: 'Lässt sich wenig ablenken',
    icon: ShieldCheck,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Bleibt auch bei Nebengeräuschen im Klassenraum fokussiert',
  },
  needs_repeated_prompt: {
    label: 'Braucht wiederholte Erinnerung',
    icon: AlertCircle,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Startet oder setzt Arbeit erst nach mehrfacher Ansprache fort',
  },
  waits_for_direct_help: {
    label: 'Wartet auf direkte Hilfe',
    icon: HelpCircle,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Wartet passiv, bis Lehrkraft an den Tisch kommt',
  },
  needs_reassurance: {
    label: 'Braucht ständige Bestätigung',
    icon: AlertCircle,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Fragt nach jedem Einzelschritt rückversichernd nach',
  },
  loses_task_focus: {
    label: 'Verliert Arbeitsfokus',
    icon: TrendingDown,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Schweift bei offenen oder längeren Arbeitsphasen ab',
  },
  stops_after_error: {
    label: 'Bricht nach Fehler ab',
    icon: AlertCircle,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Zeigt Frustration oder resigniert bei Fehlern schnell',
  },
  premature_task_abort: {
    label: 'Vorzeitiger Abbruch',
    icon: TrendingDown,
    activeBg: 'bg-rose-600',
    activeBorder: 'border-rose-700',
    activeText: 'text-white',
    description: 'Gibt Arbeitsauftrag vorzeitig unvollständig ab',
  },
  needs_step_by_step_support: {
    label: 'Braucht kleinschrittige Begleitung',
    icon: ListOrdered,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Benötigt Aufteilung in kleinste überschaubare Zwischenschritte',
  },
  needs_org_support: {
    label: 'Braucht Ordnungshilfe',
    icon: Briefcase,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Braucht Unterstützung beim Sortieren und Bereitstellen des Materials',
  },

  // =========================================================================
  // 8. SOZIALVERHALTEN (sl-sozialverhalten)
  // =========================================================================
  cooperates: {
    label: 'Kooperiert aktiv',
    icon: Users,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Bringt sich konstruktiv und hilfsbereit in Partner- oder Gruppenarbeit ein',
  },
  active_in_group: {
    label: 'Aktiv in der Gruppe',
    icon: Users,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Beteiligt sich engagiert an gemeinsamen Gruppenabsprachen',
  },
  listens_to_others: {
    label: 'Hört anderen zu',
    icon: MessageCircle,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Lässt Mitschüler ausreden und geht auf deren Beiträge ein',
  },
  takes_turns: {
    label: 'Hält Abwechseln ein',
    icon: ArrowLeftRight,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Wartet geduldig, bis er/sie an der Reihe ist',
  },
  offers_help: {
    label: 'Bietet Hilfe an',
    icon: Heart,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Unterstützt andere Kinder unaufgefordert und freundlich',
  },
  accepts_help: {
    label: 'Nimmt Hilfe dankend an',
    icon: UserCheck,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Lässt sich von Mitschülern unterstützen und bedankt sich',
  },
  expresses_needs_clearly: {
    label: 'Äußert Wünsche verständlich',
    icon: MessageSquare,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Formuliert eigene Bedürfnisse ruhig und konstruktiv',
  },
  respects_boundaries: {
    label: 'Respektiert Grenzen anderer',
    icon: ShieldCheck,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Akzeptiert ein „Stopp“ oder „Nein“ von Mitschülern sofort',
  },
  finds_compromise: {
    label: 'Findet Kompromisse',
    icon: Scale,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Sucht in Uneinigkeiten nach Lösungen, die für alle passen',
  },
  shares_materials: {
    label: 'Teilt Materialien gerne',
    icon: Heart,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Gibt Stifte, Scheren oder Spielzeug bereitwillig weiter',
  },
  shows_empathy: {
    label: 'Zeigt Empathie',
    icon: Heart,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Nimmt Gefühle anderer wahr und tröstet oder reagiert einfühlsam',
  },
  deescalates_conflict: {
    label: 'Deeskaliert Konflikte',
    icon: ShieldCheck,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Trägt in Streitigkeiten aktiv zu Beruhigung und Klärung bei',
  },
  participates_in_circle: {
    label: 'Beteiligt sich im Kreis',
    icon: Users,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Meldet sich und hört in Klassen- oder Morgenkreisen aufmerksam zu',
  },
  needs_support_in_conflict: {
    label: 'Braucht Konfliktbegleitung',
    icon: HelpCircle,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Benötigt bei Meinungsverschiedenheiten eine moderierende Lehrkraft',
  },
  interrupts_often: {
    label: 'Unterbricht häufiger',
    icon: MessageCircle,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Fällt anderen ins Wort oder ruft ohne Meldung dazwischen',
  },
  withdraws_from_group: {
    label: 'Zieht sich eher zurück',
    icon: Users,
    activeBg: 'bg-slate-600',
    activeBorder: 'border-slate-700',
    activeText: 'text-white',
    description: 'Hält sich in Gruppenarbeiten im Hintergrund oder isoliert sich',
  },
  reacts_impulsively: {
    label: 'Reagiert situativ impulsiv',
    icon: AlertCircle,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Reagiert bei Ärger oder Frust spontan laut oder körperbetont',
  },
  needs_help_with_perspective_taking: {
    label: 'Braucht Impuls für Perspektivübernahme',
    icon: Eye,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Benötigt gezielte Frage, um Sichtweise des anderen Kindes zu verstehen',
  },

  // =========================================================================
  // 9. METAKOGNITION & SELBSTEINSCHÄTZUNG (sl-metakognition)
  // =========================================================================
  assesses_self_realistically: {
    label: 'Schätzt sich realistisch ein',
    icon: CheckCircle2,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Eigene Einschätzung deckt sich gut mit der tatsächlichen Bearbeitung',
  },
  recognizes_uncertainty: {
    label: 'Erkennt eigene Unsicherheit',
    icon: Lightbulb,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Kann benennen, wo es sich noch unsicher fühlt oder zögert',
  },
  names_strategy: {
    label: 'Benennt eigene Strategie',
    icon: Brain,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Erklärt in eigenen Worten, wie es zur Lösung gelangt ist',
  },
  reflects_on_error: {
    label: 'Reflektiert über Fehler',
    icon: Sparkles,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Versteht die Ursache eines Fehlers und leitet daraus Schlüsse ab',
  },
  asks_for_help_appropriately: {
    label: 'Fordert Hilfe gezielt ein',
    icon: HelpCircle,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Weiß genau, an welchem Punkt Unterstützung benötigt wird',
  },
  identifies_next_step: {
    label: 'Benennt nächsten Lernschritt',
    icon: ArrowRight,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Kann formulieren, was es als Nächstes üben oder festigen möchte',
  },
  uses_feedback: {
    label: 'Nutzt Rückmeldungen',
    icon: ThumbsUp,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Setzt Tipps und Feedback der Lehrkraft direkt in die Tat um',
  },
  chooses_helpful_tool: {
    label: 'Wählt passendes Hilfsmittel',
    icon: Lightbulb,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Weiß, welches Anschauungs- oder Hilfsmittel ihm weiterhilft',
  },
  explains_learning_process: {
    label: 'Erklärt Denk- und Lernweg',
    icon: MessageSquare,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Beschreibt nachvollziehbar die gedanklichen Zwischenschritte',
  },
  self_assessment_matches: {
    label: 'Selbst- & Fremdeinschätzung übereinstimmend',
    icon: CheckCircle2,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Kindereinschätzung und Beobachtung der Lehrkraft stimmen überein',
  },
  cannot_name_strategy_yet: {
    label: 'Kann Vorgehen noch nicht benennen',
    icon: HelpCircle,
    activeBg: 'bg-slate-500',
    activeBorder: 'border-slate-600',
    activeText: 'text-white',
    description: 'Löst intuitiv, kann den Lösungsweg jedoch noch nicht verbalisieren',
  },
  needs_prompt_for_reflection: {
    label: 'Braucht Reflexionsimpuls',
    icon: Lightbulb,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Benötigt konkrete Fragen oder Hilfsfragen zum Nachdenken über die Aufgabe',
  },
  self_assessment_differs_from_observation: {
    label: 'Einschätzung weicht von Beobachtung ab',
    icon: Scale,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Selbsteinschätzung des Kindes und Lehrerbeobachtung unterscheiden sich aktuell',
  },

  // Ergänzungen & Spezifische Beobachtungs-Tags
  stays_on_task: {
    label: 'Bleibt konzentriert bei der Sache',
    icon: Clock,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Arbeitet zielstrebig und ohne abzuschweifen am Auftrag',
  },
  organized_workplace: {
    label: 'Gut organisierter Arbeitsplatz',
    icon: Briefcase,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Arbeitsmittel und Unterlagen sind stets ordentlich strukturiert',
  },
  persistent_with_errors: {
    label: 'Beharrlich trotz Fehlern',
    icon: RotateCw,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Lässt sich von Fehlern nicht entmutigen und probiert es weiter',
  },
  needs_prompting: {
    label: 'Benötigt Aufforderung',
    icon: AlertCircle,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Startet erst nach persönlicher Erinnerung oder Ansprache',
  },
  easily_distracted: {
    label: 'Leicht ablenkbar',
    icon: EyeOff,
    activeBg: 'bg-amber-500',
    activeBorder: 'border-amber-600',
    activeText: 'text-white',
    description: 'Lässt sich durch Umgebungsreize rasch aus dem Rhythmus bringen',
  },
  rushes_through: {
    label: 'Arbeitet überhastet',
    icon: Zap,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Eilt durch die Aufgaben ohne genaue Qualitätskontrolle',
  },
  gives_up_easily: {
    label: 'Gibt schnell auf',
    icon: TrendingDown,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Resigniert rasch bei ersten Schwierigkeiten oder Fehlern',
  },
  cooperates_actively: {
    label: 'Arbeitet aktiv zusammen',
    icon: Users,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Beteiligt sich engagiert und partnerschaftlich an der Aufgabe',
  },
  listens_attentively: {
    label: 'Hört aufmerksam zu',
    icon: MessageCircle,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Hört Beiträgen anderer konzentriert zu und lässt ausreden',
  },
  helps_others: {
    label: 'Hilft anderen hilfsbereit',
    icon: Heart,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Unterstützt Mitschüler unaufgefordert und wertschätzend',
  },
  resolves_conflicts_peacefully: {
    label: 'Löst Konflikte friedlich',
    icon: ShieldCheck,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Verwendet Worte zur Konfliktlösung oder holt sachlich Hilfe',
  },
  escalates_conflicts: {
    label: 'Konflikt eskaliert schnell',
    icon: AlertCircle,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Reagiert bei Streit rasch laut, ablehnend oder körperlich',
  },
  dominates_interaction: {
    label: 'Dominiert Interaktion',
    icon: Users,
    activeBg: 'bg-amber-600',
    activeBorder: 'border-amber-700',
    activeText: 'text-white',
    description: 'Bestimmt Entscheidungen allein und drängt andere in den Hintergrund',
  },
  refuses_cooperation: {
    label: 'Verweigert Kooperation',
    icon: AlertCircle,
    activeBg: 'bg-rose-500',
    activeBorder: 'border-rose-600',
    activeText: 'text-white',
    description: 'Lehnt Zusammenarbeit in der vorgegebenen Gruppe ab',
  },
  accepts_feedback: {
    label: 'Nimmt Feedback an',
    icon: ThumbsUp,
    activeBg: 'bg-emerald-600',
    activeBorder: 'border-emerald-700',
    activeText: 'text-white',
    description: 'Nimmt sachliche Rückmeldungen auf und setzt sie positiv um',
  },
  defensive_to_feedback: {
    label: 'Abwehrend bei Feedback',
    icon: AlertCircle,
    activeBg: 'bg-orange-500',
    activeBorder: 'border-orange-600',
    activeText: 'text-white',
    description: 'Reagiert auf sachliche Kritik gekränkt oder rechtfertigend',
  },
  withdrawn_passive: {
    label: 'Passiv / zurückgezogen',
    icon: Users,
    activeBg: 'bg-slate-600',
    activeBorder: 'border-slate-700',
    activeText: 'text-white',
    description: 'Beteiligt sich kaum von selbst am Gruppengeschehen',
  },
  chooses_appropriate_tools: {
    label: 'Wählt passende Werkzeuge',
    icon: Lightbulb,
    activeBg: 'bg-teal-600',
    activeBorder: 'border-teal-700',
    activeText: 'text-white',
    description: 'Greift selbstständig zu geeigneten Arbeits- und Hilfsmitteln',
  },
  verbalizes_thinking_process: {
    label: 'Versprachlicht Denkprozess',
    icon: MessageSquare,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Kann die eigenen Gedankengänge schlüssig in Worte fassen',
  },
  adapts_strategy: {
    label: 'Passt Strategie flexibel an',
    icon: Lightbulb,
    activeBg: 'bg-blue-600',
    activeBorder: 'border-blue-700',
    activeText: 'text-white',
    description: 'Wechselt flexibel zu einer anderen Vorgehensweise, wenn nötig',
  },
  overestimates_self: {
    label: 'Schätzt sich eher zu hoch ein',
    icon: Scale,
    activeBg: 'bg-amber-500',
    activeBorder: 'border-amber-600',
    activeText: 'text-white',
    description: 'Schätzt die eigene Leistung höher ein als in der Beobachtung sichtbar',
  },
  underestimates_self: {
    label: 'Schätzt sich eher zu vorsichtig ein',
    icon: Scale,
    activeBg: 'bg-blue-500',
    activeBorder: 'border-blue-600',
    activeText: 'text-white',
    description: 'Traut sich weniger zu, als es tatsächlich bewältigen kann',
  },
  notices_difficulties: {
    label: 'Bemerkt eigene Hürden',
    icon: Lightbulb,
    activeBg: 'bg-indigo-600',
    activeBorder: 'border-indigo-700',
    activeText: 'text-white',
    description: 'Nimmt Hürden und Knackpunkte der Aufgabe eigenständig wahr',
  },
  unaware_of_errors: {
    label: 'Nimmt Fehler noch nicht wahr',
    icon: HelpCircle,
    activeBg: 'bg-slate-500',
    activeBorder: 'border-slate-600',
    activeText: 'text-white',
    description: 'Bemerkt Unstimmigkeiten oder Fehler in der eigenen Arbeit noch nicht',
  },
};

export const DiagnosticObservationPanel: React.FC<DiagnosticObservationPanelProps> = ({
  selectedTags,
  onToggleTag,
  availableTags,
  teacherNote,
  onChangeTeacherNote,
}) => {
  const displayTags: DiagnosticObservationTag[] = availableTags && availableTags.length > 0
    ? availableTags
    : ['instant', 'strategy_used', 'counted', 'hesitant', 'needs_hint'];

  return (
    <div className="space-y-3 bg-white p-4 rounded-2xl border border-slate-200 shadow-xs">
      <div className="flex items-center justify-between">
        <label className="text-xs font-bold text-slate-700 uppercase tracking-wider">
          Beobachtete Strategien & Lösungswege
        </label>
        <span className="text-[11px] text-slate-400">
          Tippen zum Markieren
        </span>
      </div>

      {/* Observation Tag Buttons */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">
        {displayTags.map((tag) => {
          const isSelected = selectedTags.includes(tag);
          const cfg = TAG_CONFIG[tag] || {
            label: tag,
            icon: Check,
            activeBg: 'bg-indigo-600',
            activeBorder: 'border-indigo-700',
            activeText: 'text-white',
            description: '',
          };
          const Icon = cfg.icon;

          return (
            <button
              key={tag}
              type="button"
              id={`tag-btn-${tag}`}
              onClick={() => onToggleTag(tag)}
              title={cfg.description}
              className={`flex items-center gap-2 px-3 py-2.5 rounded-xl border text-xs font-semibold transition-all cursor-pointer text-left ${
                isSelected
                  ? `${cfg.activeBg} ${cfg.activeBorder} ${cfg.activeText} shadow-xs scale-[1.01]`
                  : 'bg-slate-50 border-slate-200 text-slate-700 hover:bg-slate-100 hover:border-slate-300'
              }`}
            >
              <Icon className="w-3.5 h-3.5 shrink-0" />
              <span className="truncate flex-1">{cfg.label}</span>
              {isSelected && <Check className="w-3 h-3 shrink-0" />}
            </button>
          );
        })}
      </div>

      {/* Quick Teacher Note input */}
      {onChangeTeacherNote && (
        <div className="pt-2">
          <input
            type="text"
            id="input-task-teacher-note"
            placeholder="Optionale Notiz zu dieser Aufgabe (z. B. '8+2=10 laut gedacht', 'zeigte mit Finger')..."
            value={teacherNote || ''}
            onChange={(e) => onChangeTeacherNote(e.target.value)}
            className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-lg text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:bg-white transition-colors"
          />
        </div>
      )}
    </div>
  );
};
