import React, {useRef} from 'react';
import {LessonFrame,lessonButton,useLessonState,type PracticeProps} from './LearningPracticeWidgets';
import {duelTask,awardDuel,type MathOperation,type MathLevel,type ArithmeticTask} from '../../lib/mathPracticeModel';
const primary=lessonButton+' bg-accent text-accent-text border-accent';
export function playMathTone(success:boolean){try{const AudioCtx=window.AudioContext||(window as any).webkitAudioContext;if(!AudioCtx)return;const ctx=new AudioCtx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=success?659:150;gain.gain.setValueAtTime(.035,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);osc.connect(gain);gain.connect(ctx.destination);osc.onended=()=>{void ctx.close().catch(()=>{});};osc.start();osc.stop(ctx.currentTime+.2);}catch{}}
const operations:MathOperation[]=['+','−','×','÷'];
const levels:{id:MathLevel;name:string}[]=[{id:'easy',name:'Einfach'},{id:'medium',name:'Mittel'},{id:'hard',name:'Schwer'}];
const Equation:React.FC<{task:ArithmeticTask}>=({task})=><p data-math-equation className="text-center text-4xl font-black tabular-nums">{task.left} {task.op} {task.right} = ?</p>;
export const MathduelWidgetContent:React.FC<PracticeProps>=props=>{
 const [s,set]=useLessonState(props,'mathduel',{level:'medium' as MathLevel,op:'mixed' as MathOperation|'mixed',task:duelTask('medium','mixed'),scores:[0,0],winner:null as number|null,solved:false,feedback:'Beide Teams rechnen dieselbe Aufgabe. Das erste richtige Ergebnis gibt einen Punkt.'});
 const locked=useRef(false);locked.current=s.solved||s.winner!==null;
 const restart=(patch:Partial<typeof s>={})=>set(p=>{const n={...p,...patch};locked.current=false;return {...n,task:duelTask(n.level,n.op),scores:[0,0],winner:null,solved:false,feedback:'Neues Duell: Wer erreicht zuerst fünf Punkte?'};});
 const answer=(player:number,value:number)=>{if(locked.current)return;if(value!==s.task.answer){playMathTone(false);set(p=>({...p,feedback:`Team ${player+1}: noch nicht. Ihr dürft weiterrechnen.`}));return;}locked.current=true;playMathTone(true);set(p=>({...p,...awardDuel(p.scores,player),solved:true,feedback:`Team ${player+1} erhält einen Punkt. ${p.task.left} ${p.task.op} ${p.task.right} = ${p.task.answer}.`}));};
 return <LessonFrame label="Mathe-Duell"><div className="grid shrink-0 grid-cols-3 gap-2"><select aria-label="Duell-Schwierigkeit" className={lessonButton} value={s.level} onChange={e=>restart({level:e.target.value as MathLevel})}>{levels.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select aria-label="Duell-Rechenart" className={lessonButton} value={s.op} onChange={e=>restart({op:e.target.value as typeof s.op})}><option value="mixed">Gemischt</option>{operations.map(op=><option key={op} value={op}>{op}</option>)}</select><button className={lessonButton} onClick={()=>restart()}>Neu starten</button></div><p className="shrink-0 font-bold">Bis fünf Punkte · Einstellungen starten ein neues Duell.</p><div className="flex min-h-0 flex-1 flex-col justify-center gap-5"><Equation task={s.task}/><div className="grid grid-cols-2 gap-4">{[0,1].map(player=><div key={player} className="rounded-2xl border p-3"><h3 data-team-score={player} className="mb-3 text-xl font-black">Team {player+1}: {s.scores[player]} Punkte</h3><div className="grid grid-cols-3 gap-2">{s.task.choices.map(value=><button key={value} disabled={s.solved||s.winner!==null} data-team={player} data-math-choice={value} className={lessonButton} onClick={()=>answer(player,value)}>{value}</button>)}</div></div>)}</div></div><p role="status" className="shrink-0 rounded-xl border bg-accent-soft p-3 font-semibold">{s.winner!==null?`Team ${s.winner+1} gewinnt mit fünf Punkten!`:s.feedback}</p>{s.winner===null?<button className={primary} disabled={!s.solved} onClick={()=>{locked.current=false;set(p=>({...p,solved:false,task:duelTask(p.level,p.op),feedback:'Nächste Aufgabe: Beide Teams rechnen mit.'}));}}>Nächste Duellaufgabe</button>:<button className={primary} onClick={()=>restart()}>Neues Duell</button>}</LessonFrame>;
};
